'use strict';
const assert=require('assert');
const G=require('./ui-grid.js');
assert.strictEqual(G.SCHEMA,'sss.display.ui-grid.v2');
assert.deepStrictEqual(G.ADDRESS_SYMBOLS,['w','x','y','z']);
assert.deepStrictEqual(G.bounds('w'),{x:0,y:0,w:.5,h:.5});
assert.deepStrictEqual(G.bounds('z'),{x:.5,y:.5,w:.5,h:.5});
let s=G.emptyState('demo');
s=G.split(s,'');
s=G.split(s,'w');
s=G.defineField(s,'header',['ww','wx'],'HEADER');
s=G.defineField(s,'body',['wy','wz'],'BODY');
s=G.place(s,'title',{kind:'text',field:'header',anchor:'north',rank:0,label:'TITLE'});
assert.strictEqual(s.elements.title.field,'header');
assert.deepStrictEqual(s.elements.title.cells,['ww','wx']);
s=G.defineField(s,'header',['x'],'HEADER MOVED');
assert.deepStrictEqual(s.elements.title.cells,['x'],'field-bound element must follow field redefinition');
assert.throws(()=>G.defineField(s,'body2',['wy','wz']),/already named/);
let c=G.command(s,'move title @header -> @body');
assert.strictEqual(c.state.elements.title.field,'body');
assert.deepStrictEqual(c.state.elements.title.cells,['wy','wz']);
assert.strictEqual(c.log,'move title @header -> @body');
c=G.command(c.state,'field nav = ww+wx');
assert.deepStrictEqual(c.state.fields.nav.cells,['ww','wx']);
c=G.command(c.state,'place navLabel @nav text north -1');
assert.strictEqual(c.state.elements.navLabel.field,'nav');
const round=G.parseState(G.formatState(c.state));
assert.deepStrictEqual(round,c.state);
const legacy=G.parseState(JSON.stringify({schema:'sss.display.ui-grid.v1',splits:[''],elements:{legacy:{kind:'text',cells:['w'],anchor:'north',rank:0,label:'LEGACY'}}}));
assert.strictEqual(legacy.schema,G.SCHEMA);
assert.deepStrictEqual(legacy.fields,{});
assert.deepStrictEqual(legacy.elements.legacy.cells,['w']);
assert.strictEqual(legacy.elements.legacy.field,null);
console.log('ui-grid-v2: PASS');
