(() => {
'use strict';

const id='organism:papers';
const modules=globalThis.SSSInterlocutorModules||(globalThis.SSSInterlocutorModules=new Map());
const GENES=['w','x','z','y'];
const DNA={w:'CREATE',x:'COPY',z:'CONTROL',y:'CULTIVATE'};
const geneIndex={w:0,x:1,z:2,y:3};
const N=globalThis.SSSDisplayNavigation||null;
const W=globalThis.SSSWorldView||null;

const INQUIRY=Object.freeze({
  '5H.Dw6a':{
    title:'contestable continuity-renewal lineage',
    boundary:'This is a cross-holon relational synthesis over four already-metabolized 4H organisms. Rank 5 does not upgrade their heterogeneous evidence into one mechanism, ontology, universal theorem, or guaranteed repair. Structural recurrence remains structural recurrence; replayable repair is not interior identity; quotient permission is local rather than universal; successor authority never retroactively strengthens its predecessor.',
    edges:[
      {id:'wx',title:'replication-audited replayable renewal',members:['4H.993M','4H.vPbh'],text:"A replayable renewal procedure may be treated as a recurring capacity only when recurrence is independently witnessed rather than inferred from the procedure's own self-description, while every concrete successor still has to pass the replayed tests under current conditions.",removal:'Without 4H.993M, recurrence lacks the complete executable successor-generation route; without 4H.vPbh, replayability has no independent replication or variant-constitution witness.'},
      {id:'wy',title:'quotient-addressed replayable renewal',members:['4H.993M','4H.Bbw6'],text:'Failure can address not only the warrant and scaffold that need replay but also the exact negative space of predecessor authority: distinctions previously omitted may be reopened and their nuisance status reconsidered before a successor is issued.',removal:'Without 4H.993M the quotient lacks the complete replayable successor-production route; without 4H.Bbw6 renewal cannot state which ignored distinctions must lose or re-earn nuisance status.'},
      {id:'wz',title:'provenance-bearing replay succession',members:['4H.993M','4H.3W-6'],text:'Replay becomes a version transition whose predecessor remains immutable, whose failure route stays inspectable, and whose successor carries the evidence and reconstruction path plus the fresh tests that re-authorized it.',removal:'Without 4H.993M each current warrant need not carry its own bounded recovery route; without 4H.3W-6 renewal loses the full versioned passport and fresh-successor witness.'},
      {id:'xy',title:'replication-qualified non-silent quotient adaptation',members:['4H.vPbh','4H.Bbw6'],text:'Recurring repair structure may strengthen confidence that an adaptation pattern recurs, but cannot silently promote a repeated omission into invariance. Every successor must re-earn which distinctions it may ignore under its present regime.',removal:'Without 4H.vPbh quotient re-witnessing lacks independent recurrence; without 4H.Bbw6 replication can recur while ignored-difference scope remains implicit.'},
      {id:'xz',title:'replication-qualified self-reconstitution',members:['4H.vPbh','4H.3W-6'],text:'Self-repair may be promoted as reusable structural capacity only after independent recurrence support, while each version remains separately revocable, reconstructible, and freshly witnessed.',removal:'Without 4H.vPbh self-reconstitution has no independent recurrence qualification; without 4H.3W-6 recurrence lacks the executable authority lineage that keeps repair claims revocable and re-enterable.'},
      {id:'yz',title:'quotient-indexed successor passport',members:['4H.Bbw6','4H.3W-6'],text:'A successor passport records not only how a new warrant became authorized but what it is presently permitted to omit and how those omissions can be reopened.',removal:'Without 4H.Bbw6 the passport lacks the negative-space contract of current nuisance distinctions; without 4H.3W-6 quotient provenance lacks the full executable versioned successor carrier.'}
    ],
    faces:[
      {id:'wxy',title:'replicated quotient-aware renewal',members:['4H.993M','4H.vPbh','4H.Bbw6'],text:'A repair procedure can recur across encounters without becoming self-certifying: each warrant reopens evidence implicated by failure, replays repair and retest, and separately re-witnesses any quotient whose nuisance classifications it wishes to retain.',removal:'Remove 4H.993M and executable successor replay is lost; remove 4H.vPbh and independent recurrence qualification is lost; remove 4H.Bbw6 and the gate against silent inheritance of ignored distinctions is lost.'},
      {id:'wxz',title:'replication-qualified replay lineage',members:['4H.993M','4H.vPbh','4H.3W-6'],text:'The successor-production route is executable, its reconstitution pattern has independent recurrence support, and every authority transition remains versioned, reflexively falsifiable, and freshly witnessed.',removal:'Remove 4H.993M and current warrants need not carry their own successor route; remove 4H.vPbh and recurrence is no longer independently audited; remove 4H.3W-6 and the executable predecessor/current/successor contract disappears.'},
      {id:'wyz',title:'address-complete successor renewal',members:['4H.993M','4H.Bbw6','4H.3W-6'],text:'Renewal can reopen both the positive body of the failed contract and the negative space that contract had licensed away, while preserving versioned provenance, falsifiers, reconstruction, and fresh authority.',removal:'Remove 4H.993M and the self-carried recovery program is lost; remove 4H.Bbw6 and ignored-difference addressability is lost; remove 4H.3W-6 and the full successor passport is lost.'},
      {id:'xyz',title:'replication-qualified quotient-indexed lineage',members:['4H.vPbh','4H.Bbw6','4H.3W-6'],text:'A self-reconstituting lineage can be independently recurrent while its versions explicitly expose what they are permitted to ignore. Recurrence supports a capacity only while each successor remains versioned, freshly witnessed, and accountable for its nuisance quotient.',removal:'Remove 4H.vPbh and independent recurrence is lost; remove 4H.Bbw6 and successors can silently inherit omissions; remove 4H.3W-6 and the relation no longer closes as an executable reflexive authority lineage.'}
    ],
    volume:{id:'wxyz',title:'contestable continuity-renewal lineage',members:['4H.993M','4H.vPbh','4H.Bbw6','4H.3W-6'],text:'The complete closure separates four conditions that lower-rank repair can otherwise collapse into one reassuring word such as continuity: the ability to produce a successor after failure, evidence that the repair relation actually recurs across independent encounters, an explicit account of which distinctions a current warrant may ignore, and a versioned/reflexive authority lineage that can revoke and reconstitute itself. What persists is not one carrier, mechanism, quotient, scaffold, repair recipe, or warrant. What persists is the bounded capacity to produce, challenge, localize, revise, replicate, and freshly authorize the conditions under which continuity may count again.',invariant:'A higher-order continuity-renewal lineage is warranted only when every current warrant carries an executable failure→reacquisition→revision→retest route for producing a successor; the repair relation has independent recurrence support; every successor re-witnesses the distinctions it may ignore and preserves addresses back to omitted evidence; and predecessor/current/successor authority remains versioned, reflexively falsifiable, provenance-preserving, and freshly witnessed. Renewal remains living precisely because the law by which continuity is renewed stays contestable.',removal:['Remove 4H.993M: the closure loses the requirement that every current warrant itself carry an executable successor-production and retest route.','Remove 4H.vPbh: the closure loses independent same- and variant-constellation recurrence support.','Remove 4H.Bbw6: the closure loses the ledger of ignored distinctions and the requirement that a successor re-earn nuisance status.','Remove 4H.3W-6: the closure loses the versioned/reflexive successor passport that keeps predecessor authority immutable and admits a successor only after fresh reconstruction and witness.']},
    metabolites:[
      {id:'INV-5H.Dw6a-01',title:'REPLICATION-AUDITED-RENEWAL',earning:'wx',strengthened_by:'wxz',members:['4H.993M','4H.vPbh'],text:'A replayable successor-production procedure may be promoted as reusable renewal capacity only when its repair relation is independently witnessed to recur across encounters or constitutions, while every concrete successor remains separately subject to current replay and authority tests.',compression:'A repair law becomes reusable only when it can both replay and survive independent recurrence.'},
      {id:'INV-5H.Dw6a-02',title:'NON-SILENT-SUCCESSOR-PASSPORT',earning:'yz',strengthened_by:'wyz',members:['4H.Bbw6','4H.3W-6'],text:'Every successor continuity passport must carry predecessor provenance, its evidence and reconstruction route, falsifiers and fresh authority witness, plus the explicit local quotient of distinctions it is presently permitted to ignore and the addresses by which those omissions can be reopened.',compression:'A successor must carry what it may ignore as explicitly as what it promises.'},
      {id:'INV-5H.Dw6a-03',title:'CONTESTABLE-SELF-RENEWING-LINEAGE',earning:'wxyz',members:['4H.993M','4H.vPbh','4H.Bbw6','4H.3W-6'],text:'A continuity lineage is self-renewing only while the law that renews it remains contestable by executable failure and replay, independent recurrence evidence, explicit quotient re-witnessing, and versioned reflexive successor authority. Failure of any one channel must be able to stop or revise continuation without rewriting predecessor history.',compression:'Continuity stays alive by keeping its own renewal law open to being wrong.'}
    ]
  },
  '4H.993M':{
    title:'replayable continuity-renewal lineage',
    edges:[
      {id:'wx',title:'replayable version succession',members:['3H.x3Cd','3H.UoYa'],text:'After a classified invalidation, the current version can freeze as provenance while its carried replay procedure is used to build and independently witness the next version.',removal:'Without x3Cd succession loses its portable executable replay body; without UoYa replay lacks explicit version authority and a rule for when predecessor authority ends.'},
      {id:'wy',title:'executable evidence-backed successor reconstruction',members:['3H.x3Cd','3H.ZwWN'],text:'Revocation can reopen the exact evidence and reconstructive body implicated by a failed typed contract, rebuild the relation, and rerun its tests before authority returns.',removal:'Without x3Cd the reconstruction is not an executable replay procedure; without ZwWN there is no typed frontier-conditioned object specifying what must be rebuilt.'},
      {id:'wz',title:'replay-directed dual revision',members:['3H.x3Cd','3H.M9zZ'],text:"Replay may first reopen evidence and co-revise scaffold plus transition law, then rerun the obligation and pressure tests on the repaired realization rather than merely replaying yesterday's machinery.",removal:'Without x3Cd dual revision lacks a replay passport; without M9zZ replay cannot earn joint revision of scaffold and transition family from reacquired tissue.'},
      {id:'xy',title:'boundary-conditioned successor contract',members:['3H.UoYa','3H.ZwWN'],text:'A successor contract is created only after an event is classified as warrant-breaking and the revised typed obligation is reconstructed and pressure-tested against the changed frontier or regime.',removal:'Without UoYa reconstruction lacks version-transition authority; without ZwWN version transition lacks the evidence-backed typed contract and frontier.'},
      {id:'xz',title:'versioned renewal cycle',members:['3H.UoYa','3H.M9zZ'],text:'The predecessor freezes as provenance, repair may reopen omitted tissue and revise realizational law, and only a freshly tested candidate becomes the next current warrant.',removal:'Without UoYa renewal lacks explicit version succession; without M9zZ succession lacks reacquirable co-revision when the old scaffold or mapping is part of the failure.'},
      {id:'yz',title:'frontier-repair co-revision',members:['3H.ZwWN','3H.M9zZ'],text:'Repair may alter both what is retained and how it is translated when the old frontier or regime fails, while the revised public contract must still pass current pressure.',removal:'Without ZwWN co-revision lacks a typed frontier-conditioned contract and authority gate; without M9zZ reconstruction cannot reopen omitted material and revise scaffold plus transition law together.'}
    ],
    faces:[
      {id:'wxy',title:'versioned replayable successor reconstruction',members:['3H.x3Cd','3H.UoYa','3H.ZwWN'],text:'A warrant-breaking event is classified against the current version and frontier, the predecessor is retained unchanged, implicated evidence is reacquired and reconstructed, and carried replay tests decide whether a candidate successor may become current.',removal:'Remove x3Cd and executable replay is lost; remove UoYa and explicit authority succession is lost; remove ZwWN and the typed evidence-backed reconstruction target is lost.'},
      {id:'wxz',title:'replayable warrant-renewal lifecycle',members:['3H.x3Cd','3H.UoYa','3H.M9zZ'],text:"The failure path itself is executable: classify invalidation, preserve the expired version, reopen dormant evidence where needed, co-revise scaffold and transition law, and rerun the predecessor's tests before issuing a successor.",removal:'Remove x3Cd and renewal is no longer executable state; remove UoYa and versioned authority transition disappears; remove M9zZ and repair cannot co-revise machinery from reacquired tissue.'},
      {id:'wyz',title:'executable evidence-backed repair program',members:['3H.x3Cd','3H.ZwWN','3H.M9zZ'],text:'A bounded repair program starts from a failed typed contract, preserves exact evidence addresses, reopens newly relevant dormant material, revises scaffold and transformation law where pressure demands, and reruns composite and frontier tests without claiming interior identity.',removal:'Remove x3Cd and replayable evidence/test state is lost; remove ZwWN and the typed successor gate is lost; remove M9zZ and reacquisition-backed co-revision is lost.'},
      {id:'xyz',title:'frontier-classified co-revisionary successor contract',members:['3H.UoYa','3H.ZwWN','3H.M9zZ'],text:'Scope change is classified before repair, the frontier and evidence body define what must be retested, and scaffold plus transition family may be revised together from reacquired tissue before a fresh successor is admitted.',removal:'Remove UoYa and explicit succession is lost; remove ZwWN and the typed frontier target is lost; remove M9zZ and realizational machinery cannot be co-revised.'}
    ],
    volume:{id:'wxyz',title:'replayable continuity-renewal lineage',members:['3H.x3Cd','3H.UoYa','3H.ZwWN','3H.M9zZ'],text:'Every current warrant carries not only its scoped operational and evidential contract but a bounded executable route for producing a successor if that warrant becomes invalid. On failure or verified boundary change, predecessor authority freezes as provenance; the event is classified against the frontier, regime and scaffold; newly load-bearing evidence is reacquired; contract, scaffold and transition family are revised as necessary; pressure and composite tests are replayed; and a freshly scoped successor is issued only after witness. Continuity persists as a lineage of re-earned warrants, not silent transfer of expired authority.',invariant:'A continuity lineage across repeated realization change is warranted only when every current warrant carries its scoped contract and an executable successor-production route after invalidation, including classified failure, reacquirable evidence, revisable contract/scaffold/transition law, rerun tests, and freshly scoped successor authority.',removal:['Remove 3H.x3Cd: the portable executable recovery passport is lost.','Remove 3H.UoYa: explicit version authority and predecessor/current/successor semantics are lost.','Remove 3H.ZwWN: the typed frontier-conditioned reconstruction target and evidence-gated successor body are lost.','Remove 3H.M9zZ: reacquirable dormant-body repair and joint scaffold/transition revision are lost.']},
    metabolites:[
      {id:'INV-4H.993M-01',title:'FAILURE-ADDRESSABLE-REPLAY',earning:'wy',strengthened_by:'wxy',members:['3H.x3Cd','3H.ZwWN'],text:'When a continuity warrant fails, its failure class, evidence and reconstruction addresses, and falsifying tests must remain executable enough to reopen the relevant body and rerun the conditions required for a successor.',compression:'A failure that cannot address its own repair evidence cannot reliably seed a successor.'},
      {id:'INV-4H.993M-02',title:'CO-REVISED-SUCCESSOR-ISSUANCE',earning:'xyz',strengthened_by:'wxyz',members:['3H.UoYa','3H.ZwWN','3H.M9zZ'],text:'After frontier, regime, or scaffold failure, successor authority is issued only after relevant evidence is reacquired, public contract and realizational machinery are revised as needed, and the new composite passes fresh pressure tests while the predecessor remains unchanged provenance.',compression:'Repair the relation and its realization law together when failure demands it; then issue new authority.'},
      {id:'INV-4H.993M-03',title:'SELF-RENEWING-CONTINUITY-LINEAGE',earning:'wxyz',members:['3H.x3Cd','3H.UoYa','3H.ZwWN','3H.M9zZ'],text:'Each accepted continuity version may participate in a self-renewing lineage only when it includes the bounded recovery passport, provenance, evidence addresses, and tests required to create and validate its own successor after invalidation.',compression:'Continuity becomes renewable when every current warrant carries a lawful way to stop being current and to seed the next one.'}
    ]
  },
  '4H.vPbh':{
    title:'replication-qualified adaptive continuity reconstitution',
    boundary:"This rank-4 body preserves heterogeneous evidence classes and treats repeated closure as structural replication under the organism's derivational contract, not as proof of one hidden mechanism, universality, uniqueness, or interior identity.",
    edges:[
      {id:'wx',title:'typed obligation meets quotient-addressed repair',members:['3H.DfDL','3H.5yyB'],text:'Failure can identify both the permission that ceased to hold and the typed public obligation a rebuilt relation must satisfy before authority returns.',removal:'Without DfDL the explicit role-typed composite obligation is lost; without 5yyB the local quotient that identifies ignored differences is lost.'},
      {id:'wy',title:'reacquisition coupled to revision of repair machinery',members:['3H.DfDL','3H.M9zZ'],text:'Re-entering the evidential body may revise not only the candidate state but the scaffold and admissible transition family by which the successor is reconstructed and tested.',removal:'Without DfDL exact revocation-to-evidence return and typed target disappear; without M9zZ repair may preserve stale scaffold or transition law.'},
      {id:'wz',title:'independent typed-obligation / quotient-address repair witness',members:['3H.DfDL','3H.DWia'],text:'A distinct quotient-addressable organism independently earns the same contract-plus-quotient repair class, adding organism-level recurrence without identity collapse.',removal:'Without DfDL the typed composite obligation is lost; without DWia the independent quotient-addressable witness is lost.'},
      {id:'xy',title:'quotient failure can drive dual revision',members:['3H.5yyB','3H.M9zZ'],text:'Reopening a failed nuisance permission can force revision not only of what counts as nuisance but of the scaffold and transformation law that made the old quotient operational.',removal:'Without 5yyB no expired permission identifies distinctions to reconsider; without M9zZ scaffold and transition family need not be revised together.'},
      {id:'xz',title:'same-constellation structural replication',members:['3H.5yyB','3H.DWia'],text:'Two distinct ACTIVE organisms born in separate encounters from the same unordered parent constellation independently converge on quotient-addressable continuity reconstitution, yielding a bounded replication witness without deduplicating them.',removal:'Without either organism only one witnessed instance remains, so same-constellation replication disappears.'},
      {id:'yz',title:'independent quotient-conditioned dual-revision witness',members:['3H.M9zZ','3H.DWia'],text:'An independently born quotient-addressable membrane joins dual machinery revision, providing another route by which expired nuisance permission can feed a repair that revises regeneration machinery rather than rerunning it unchanged.',removal:'Without M9zZ dual machinery revision is lost; without DWia the independent quotient-addressable reconstitution witness is lost.'}
    ],
    faces:[
      {id:'wxy',title:'addressed adaptive reconstitution',members:['3H.DfDL','3H.5yyB','3H.M9zZ'],text:'Revocation can identify what permission failed, reopen the relevant evidential body, revise quotient-sensitive scaffold and transition family, and retest the exact public obligation before successor authority is issued.',removal:'Remove DfDL and the typed composite target is lost; remove 5yyB and the address of failed permission is lost; remove M9zZ and repair machinery itself cannot be revised.'},
      {id:'wxz',title:'replication-qualified cross-constellation reconstitution',members:['3H.DfDL','3H.5yyB','3H.DWia'],text:'Same-parent replication of quotient-addressable reconstitution is held together with a differently constituted route to the broader revocation→reacquisition→retest family, strengthening structural recurrence beyond either witness alone.',removal:'Remove either replicated quotient-addressable organism and same-constellation replication disappears; remove DfDL and recurrence outside that repeated parent set disappears.'},
      {id:'wyz',title:'independently addressed adaptive reconstitution',members:['3H.DfDL','3H.M9zZ','3H.DWia'],text:'Typed reacquisition, dual scaffold/transition revision, and an independently born quotient-addressable membrane converge on the same adaptive repair class through a distinct route.',removal:'Remove DfDL and typed reconstitution is lost; remove M9zZ and repair machinery cannot be jointly revised; remove DWia and the explicit failed-quotient address disappears.'},
      {id:'xyz',title:'replication-qualified quotient renewal',members:['3H.5yyB','3H.M9zZ','3H.DWia'],text:'A repeatedly witnessed quotient-addressable repair may count as recurring structural capacity while its concrete regenerative scaffold and transition law remain revisable.',removal:'Remove either 5yyB or DWia and replication disappears; remove M9zZ and the relation loses dual revision that prevents repeated closure from freezing one repair implementation.'}
    ],
    volume:{id:'wxyz',title:'replication-qualified adaptive continuity reconstitution',members:['3H.DfDL','3H.5yyB','3H.M9zZ','3H.DWia'],text:'The complete closure separates repetition of one repair closure, recurrence across differently constituted closures, and adaptation of the machinery that performs repair. A continuity-repair relation may be carried forward as higher-order capacity only when same-constellation replication and a differently constituted route both witness recurrence while current evidence can still revise the scaffold and admissible transition law. What persists is not one quotient, map, carrier, or interior, but the bounded ability to identify failed authority, reopen implicated evidence, reconstruct under a current contract, revise machinery when its regime expires, retest, and issue newly scoped authority without rewriting earlier warrants.',invariant:'Higher-order continuity reconstitution is replication-qualified only when the same parent constellation independently re-earns the closure, a differently constituted constellation reaches the broader repair family, and repair machinery remains revisable when current evidence or regime invalidates it.',removal:['Remove 3H.DfDL: the differently constituted typed-contract route beyond the repeated quotient-parent set is lost.','Remove 3H.5yyB: the second independent same-parent witness required for replication is lost.','Remove 3H.M9zZ: the rule permitting scaffold and transition-family revision is lost.','Remove 3H.DWia: same-constellation replication again collapses to one instance.']},
    metabolites:[
      {id:'INV-4H.vPbh-01',title:'SAME-CONSTELLATION-REPLICATION',earning:'xz',members:['3H.5yyB','3H.DWia'],text:'When two independent same-rank organisms are separately born from the same unordered parent constellation and materially re-earn the same relational closure, their coexistence is a replication witness rather than grounds for deduplicating identity.',compression:'Repeated closure can strengthen a relation without making two births one organism.'},
      {id:'INV-4H.vPbh-02',title:'VARIANT-CONSTELLATION-ROBUSTNESS',earning:'wxz',members:['3H.DfDL','3H.5yyB','3H.DWia'],text:'A structural repair relation has stronger organism-level recurrence when same-constellation replication is joined by a differently constituted parent set preserving the broader operational cycle while changing which lower-rank component carries it.',compression:'Replay plus parent substitution is stronger recurrence than replay alone.'},
      {id:'INV-4H.vPbh-03',title:'REPLICATION-QUALIFIED-ADAPTIVE-RECONSTITUTION',earning:'wxyz',members:['3H.DfDL','3H.5yyB','3H.M9zZ','3H.DWia'],text:"A recurring continuity-repair relation counts as adaptive higher-order capacity only when recurrence is independently replicated, survives a differently constituted route, and can revise the scaffold or transition machinery that would otherwise freeze yesterday's repair into today's assumption.",compression:'The repair relation may recur; its machinery must still be allowed to evolve.'}
    ]
  },
  '4H.Bbw6':{
    title:'quotient-indexed self-reconstituting continuity lineage',
    boundary:'This body treats quotient, warrant, version, repair and successor as bounded operational-relational terms. Rank 4 does not convert them into universal mechanism, ontology, guaranteed repair, or interior identity.',
    edges:[
      {id:'wx',title:'quotient-scoped version succession',members:['3H.DWia','3H.UoYa'],text:'Each continuity version can preserve the exact quotient scope it authorized; when authority changes, the expired quotient remains provenance and a possible repair address instead of disappearing.',removal:'Without DWia there is no explicit record of which differences the version could ignore; without UoYa quotient repair lacks predecessor/current/successor authority.'},
      {id:'wy',title:'revocation-indexed repair address',members:['3H.DWia','3H.DfDL'],text:'The failed obligation can be intersected with the old quotient to identify which evidence or roles must reopen, making repair targeted rather than a generic rollback.',removal:'Without DWia repair loses ignored-difference localization; without DfDL the address exists but no exact reconstitution path is earned.'},
      {id:'wz',title:'reflexive quotient membrane',members:['3H.DWia','3H.k0uZ'],text:'What a contract may ignore becomes part of its own audit, while quotient, transition map, and retained scaffold may fail or be revised for different reasons.',removal:'Without DWia the contract cannot state its licensed nuisance distinctions; without k0uZ quotient failure lacks the full self-carried invalidation and dual-revision membrane.'},
      {id:'xy',title:'reconstitution becomes versioned succession',members:['3H.UoYa','3H.DfDL'],text:'A revoked version can produce a separately evidenced successor only after implicated tissue is reopened and the repaired relation survives current tests, while predecessor authority remains immutable provenance.',removal:'Without UoYa repair loses version authority and scope classification; without DfDL version expiry lacks an exact evidence reconstitution path.'},
      {id:'xz',title:'self-retiring continuity version',members:['3H.UoYa','3H.k0uZ'],text:'A current version can carry the conditions under which it retires itself and identify which validity machinery needs revision, distinguishing within-version adaptation from rupture requiring successor authority.',removal:'Without UoYa predecessor/current/successor authorization disappears; without k0uZ version transition depends on failure interpretation external to the contract.'},
      {id:'yz',title:'reconstitution must rebuild its invalidation machinery',members:['3H.DfDL','3H.k0uZ'],text:'Repair must rebuild not only the public relation but also the falsifiers, regime or map assumptions, and scaffold-revision channels by which the repaired relation can later be revoked.',removal:'Without DfDL no post-failure reconstitution path is earned; without k0uZ a repaired relation can lose its reflexive invalidation and revision machinery.'}
    ],
    faces:[
      {id:'wxy',title:'quotient-indexed successor reconstitution',members:['3H.DWia','3H.UoYa','3H.DfDL'],text:"The predecessor's equivalence scope indexes repair: rupture retires current authority, failed quotient exposes formerly ignored distinctions, implicated evidence is reopened and reconstructed, and a successor is admitted only after current retest.",removal:'Remove DWia and repair loses ignored-difference scope; remove UoYa and authority succession disappears; remove DfDL and exact reacquisition/reconstitution disappears.'},
      {id:'wxz',title:'reflexive versioned equivalence membrane',members:['3H.DWia','3H.UoYa','3H.k0uZ'],text:'A warrant version carries both what it promises and what it may ignore, plus the falsifiers and revision channels that can invalidate either; failed nuisance assumptions remain inspectable historical state.',removal:'Remove DWia and quotient provenance disappears; remove UoYa and version succession disappears; remove k0uZ and self-carried falsification and dual revision disappear.'},
      {id:'wyz',title:'self-repairing quotient contract',members:['3H.DWia','3H.DfDL','3H.k0uZ'],text:'A failed quotient can reopen exact omitted evidence, revise quotient, transition map and scaffold, reconstruct the public relation, and retest both the relation and the machinery that can invalidate it again.',removal:'Remove DWia and ignored-difference localization disappears; remove DfDL and exact reconstitution disappears; remove k0uZ and reflexive validity reconstruction disappears.'},
      {id:'xyz',title:'self-reconstituting version lineage',members:['3H.UoYa','3H.DfDL','3H.k0uZ'],text:'Failure is classified, revoked predecessor authority is preserved, implicated evidence is reopened, the appropriate map or scaffold channel is revised, and a successor is admitted only after fresh witness.',removal:'Remove UoYa and explicit version lineage disappears; remove DfDL and exact reconstitution disappears; remove k0uZ and reflexive diagnosis/revision disappears.'}
    ],
    volume:{id:'wxyz',title:'quotient-indexed self-reconstituting continuity lineage',members:['3H.DWia','3H.UoYa','3H.DfDL','3H.k0uZ'],text:'The complete closure turns the negative space of continuity—the distinctions a current warrant is explicitly permitted to ignore—into living lineage state. A current warrant carries obligation, evidence and reacquisition body, validity regime, reconstruction machinery, falsifiers, support scope, and an explicit local quotient. On rupture, expired warrant and quotient remain immutable provenance; their failure routes reacquisition toward implicated evidence and roles; quotient, transition map and scaffold are revised according to the witnessed failure; and a successor gains authority only after fresh witness. A successor cannot silently inherit its predecessor’s omissions: every retained nuisance classification must be warranted again.',invariant:'A continuity lineage is lawfully self-reconstituting only when every warrant carries its operational body and falsifiers, an explicit nuisance quotient, stable addresses from revoked warrant and quotient back to evidence and roles, and explicit version succession. A successor must re-earn both the public relation and what it is allowed to ignore.',removal:['Remove 3H.DWia: quotient history, ignored-difference ledger, and non-silent nuisance re-witnessing are lost.','Remove 3H.UoYa: predecessor/current/successor authority and rupture classification are lost.','Remove 3H.DfDL: exact evidence reacquisition and post-failure reconstitution are lost.','Remove 3H.k0uZ: self-falsification and distinct map-versus-scaffold revision machinery are lost.']},
    metabolites:[
      {id:'INV-4H.Bbw6-01',title:'REVOCATION-ADDRESS-CAPSULE',earning:'wx',members:['3H.DWia','3H.UoYa'],text:'Every warrant version should preserve its exact local quotient, the distinctions currently licensed as nuisance, stable evidence and role return addresses for those distinctions, and the reason authority can be revoked, so failure yields an executable repair address rather than only a verdict.',compression:'A failed warrant should carry the map of what it had permission to ignore.'},
      {id:'INV-4H.Bbw6-02',title:'TARGETED-SUCCESSOR-RECONSTITUTION',earning:'wxy',members:['3H.DWia','3H.UoYa','3H.DfDL'],text:'A successor version is authorized only after failed predecessor and quotient route reacquisition of implicated evidence, quotient or scaffold revision, and current-regime retest while predecessor warrant and quotient remain provenance.',compression:'Let the expired quotient route the evidence that earns the successor.'},
      {id:'INV-4H.Bbw6-03',title:'NON-SILENT-QUOTIENT-INHERITANCE',earning:'wxyz',members:['3H.DWia','3H.UoYa','3H.DfDL','3H.k0uZ'],text:"A successor may classify a distinction as ignorable only after that nuisance status is re-witnessed under the successor's regime, scope, reconstruction and reflexive falsification machinery; unchanged omission is not automatic continuity.",compression:'Every successor must state what it is still allowed to ignore.'}
    ]
  },
  '4H.3W-6':{
    title:'self-reconstituting continuity lineage',
    boundary:'This body treats continuity as an evidence-bounded, revocable and re-witnessed public relation. It does not claim unbroken sameness, guaranteed recovery, one persisting interior, or a universal repair mechanism.',
    edges:[
      {id:'wx',title:'repair becomes versioned succession',members:['3H.DfDL','3H.UoYa'],text:'Repair after warrant failure yields a separately evidenced successor version rather than silently modifying the predecessor, whose authority and scope remain historical provenance.',removal:'Without DfDL version expiry lacks targeted reacquisition and repair; without UoYa successful repair lacks predecessor/successor authority and change classification.'},
      {id:'wy',title:'revocation conditions can route repair',members:['3H.DfDL','3H.k0uZ'],text:'The reason continuity failed selects which evidence or scaffold tissue is reopened and which revision channel is exercised, making reconstitution failure-directed rather than generic.',removal:'Without DfDL self-revocation has no exact reconstitution path; without k0uZ reacquisition lacks reflexive diagnosis of map mismatch versus obsolete scaffold.'},
      {id:'wz',title:'a replayable passport can be a recovery program',members:['3H.DfDL','3H.x3Cd'],text:'Portable continuity state can reopen the evidence needed to rebuild itself after revocation instead of only proving that the old warrant failed.',removal:'Without DfDL the passport cannot require targeted reopening of dormant evidence; without x3Cd reconstitution is not packaged as portable executable state.'},
      {id:'xy',title:'continuity authority can version itself from witnessed failure',members:['3H.UoYa','3H.k0uZ'],text:'A contract can distinguish admissible within-version change from failure requiring a successor and can identify which validity machinery must change.',removal:'Without UoYa reflexive failure lacks version succession; without k0uZ version transition depends on failure interpretation external to the contract.'},
      {id:'xz',title:'the executable passport can carry lineage, not only a current warrant',members:['3H.UoYa','3H.x3Cd'],text:'The current warrant travels with the evidence and test path that produced it and with the predecessor it superseded, yielding a versioned executable passport.',removal:'Without UoYa replay lacks version lineage; without x3Cd version history lacks a portable procedure for re-earning current authority.'},
      {id:'yz',title:'portability can include its own audit and revision membrane',members:['3H.k0uZ','3H.x3Cd'],text:'A portable contract carries the reason continuity presently counts together with conditions that can revoke it and revise its reconstruction map or scaffold.',removal:'Without k0uZ the passport lacks reflexive map/scaffold revision; without x3Cd reflexive continuity lacks an executable portable carrier.'}
    ],
    faces:[
      {id:'wxy',title:'failure-classified successor reconstitution',members:['3H.DfDL','3H.UoYa','3H.k0uZ'],text:'Failure is detected and classified, implicated dormant evidence is reopened, the appropriate map or scaffold channel is revised, the rebuilt relation is retested, and only then may a successor version be issued while the predecessor remains intact.',removal:'Remove DfDL and exact reacquisition disappears; remove UoYa and predecessor/successor authority disappears; remove k0uZ and self-carried invalidation plus dual revision disappear.'},
      {id:'wxz',title:'replayable repair lineage',members:['3H.DfDL','3H.UoYa','3H.x3Cd'],text:'A portable audit chain runs from expired warrant through targeted reacquisition and reconstruction to a tested successor passport, preserving the evidence, failure, reopened tissue and replay tests at each transition.',removal:'Remove DfDL and exact repair path is lost; remove UoYa and explicit version succession is lost; remove x3Cd and the lineage ceases to be executable replay state.'},
      {id:'wyz',title:'self-repairing replay kernel',members:['3H.DfDL','3H.k0uZ','3H.x3Cd'],text:'A portable kernel carries both its own invalidity conditions and evidence hooks for repair, allowing failure to open targeted evidence, revise map or scaffold, rebuild and replay tests without assuming a fixed interior.',removal:'Remove DfDL and targeted evidence reopening disappears; remove k0uZ and reflexive diagnosis/revision disappears; remove x3Cd and repair is no longer carried as executable state.'},
      {id:'xyz',title:'self-versioning portable warrant',members:['3H.UoYa','3H.k0uZ','3H.x3Cd'],text:'A portable continuity object knows which warrant version is current, preserves predecessor provenance, carries revocation tests, and can fork a successor after classified boundary, regime, or scaffold change.',removal:'Remove UoYa and version lineage disappears; remove k0uZ and reflexive map/scaffold invalidation disappears; remove x3Cd and the lifecycle loses its executable replay carrier.'}
    ],
    volume:{id:'wxyz',title:'self-reconstituting continuity lineage',members:['3H.DfDL','3H.UoYa','3H.k0uZ','3H.x3Cd'],text:'All four parents turn continuity authority from a single reflexive, versioned, replayable warrant into a regenerable lineage. Each current executable contract carries conditions that can invalidate it, preserves predecessor history, and retains enough addressable evidence and scaffold state to attempt successor reconstruction. On failure the lineage classifies rupture, preserves the expired warrant as bounded provenance, reopens only implicated evidence and roles, revises map or scaffold as warranted, rebuilds and replays current tests, and admits a successor only after fresh witness. Continuity is the preserved capacity to explain, revoke, reconstruct and re-earn its own authority across generations of warrants.',invariant:'A changing realization counts as one continuing public relation across successive failures and repairs only when each current warrant is executable and replayable, reflexively falsifiable under declared conditions, explicitly versioned against preserved predecessors, and backed by addressable evidence or scaffold tissue sufficient for targeted reconstitution after revocation.',removal:['Remove 3H.DfDL: targeted evidence reacquisition and reconstitution after failure are lost.','Remove 3H.UoYa: explicit predecessor/current/successor authority and change classification are lost.','Remove 3H.k0uZ: reflexive validity machinery and distinct map-versus-scaffold revision are lost.','Remove 3H.x3Cd: the portable executable continuity passport is lost.']},
    metabolites:[
      {id:'INV-4H.3W-6-01',title:'REVOCATION-ROUTED-SUCCESSION',earning:'wxy',members:['3H.DfDL','3H.UoYa','3H.k0uZ'],text:'When a current warrant fails, failure classification should determine both which evidential or scaffold tissue reopens and whether the result is a repaired within-scope realization or a separately authorized successor version; the predecessor remains provenance.',compression:'Let the reason for revocation route the next lawful warrant.'},
      {id:'INV-4H.3W-6-02',title:'EXECUTABLE-SUCCESSOR-PASSPORT',earning:'wxz',members:['3H.DfDL','3H.UoYa','3H.x3Cd'],text:'A successor warrant is portable only when it carries the new obligation together with predecessor provenance, the reacquisition and reconstruction path used after failure, and the replay tests whose fresh success earned current authority.',compression:'A successor passport carries how it became authorized.'},
      {id:'INV-4H.3W-6-03',title:'SELF-RECONSTITUTING-CONTINUITY-LINEAGE',earning:'wxyz',members:['3H.DfDL','3H.UoYa','3H.k0uZ','3H.x3Cd'],text:'Durable continuity across repeated carrier, regime, or scaffold changes is a re-enterable lineage process when each warrant can expose its revocation conditions, classify rupture, reopen implicated evidence, revise appropriate reconstruction machinery, replay tests, and append a newly authorized successor while preserving prior scopes.',compression:'Continuity survives by keeping the path to re-earn continuity alive.'}
    ]
  }
});

const shader=Object.freeze({
  id:'shader:organism:papers',
  clear:[0.004,0.007,0.009,1],
  fallbackAlpha:.11,
  state:Object.freeze({blend:false,depthTest:true,depthWrite:true}),
  decorate({element}){
    if(element.querySelector('.papers-optics'))return;
    const optics=document.createElement('div');optics.className='papers-optics';optics.setAttribute('aria-hidden','true');
    Object.assign(optics.style,{position:'absolute',inset:'0',zIndex:'1',overflow:'hidden',pointerEvents:'none'});
    const pane=(edge)=>{
      const n=document.createElement('i');n.className='papers-defocus papers-defocus-'+edge;
      Object.assign(n.style,{position:'absolute',left:'-8%',width:'116%',height:'48%',display:'block',background:'rgba(5,7,10,.025)',backdropFilter:'blur(7px) saturate(.86)',webkitBackdropFilter:'blur(7px) saturate(.86)',transform:'rotate(-2.2deg) scale(1.04)',transformOrigin:'50% 50%'});
      if(edge==='top'){n.style.top='-15%';n.style.maskImage='linear-gradient(to bottom,#000 0%,#000 32%,transparent 100%)';n.style.webkitMaskImage=n.style.maskImage}
      else{n.style.bottom='-15%';n.style.maskImage='linear-gradient(to top,#000 0%,#000 32%,transparent 100%)';n.style.webkitMaskImage=n.style.maskImage}
      return n;
    };
    optics.append(pane('top'),pane('bottom'));
    const labels=element.querySelector('.interlocutor-field-labels');element.insertBefore(optics,labels||null);
  },
  fragment:`#version 300 es
precision highp float;
in vec3 vN;
in vec3 vW;
in float vRegion;
uniform float uTime;
uniform float uFocus;
uniform vec2 uResolution;
uniform vec3 uPalette[4];
out vec4 outColor;
float hash21(vec2 p){p=fract(p*vec2(.1031,.11369));p+=dot(p,p.yx+19.19);return fract((p.x+p.y)*p.x);}
void main(){
  vec3 n=normalize(vN);
  vec3 eye=normalize(vec3(0.,0.,3.15)-vW);
  float fres=pow(1.-abs(dot(n,eye)),2.0);
  int ri=int(clamp(floor(vRegion+.5),0.,3.));
  vec3 c=uPalette[ri];
  vec2 uv=gl_FragCoord.xy/max(uResolution,vec2(1.));
  float focal=.53+(uv.x-.5)*.10;
  float distanceFromPlane=abs(uv.y-focal);
  float sharp=1.-smoothstep(.075,.31,distanceFromPlane);
  float selected=(uFocus<-.5||abs(vRegion-uFocus)<.2)?1.:.18;
  float structural=.5+.5*sin((vW.x*1.5+vW.y*2.1-vW.z*.7)*36.+vRegion*1.8);
  float micro=.5+.5*sin((vW.x-vW.z)*118.-uTime*.035);
  float grain=(hash21(gl_FragCoord.xy+floor(uTime*4.))-.5)*(.006+.012*sharp);
  vec3 base=mix(vec3(.004,.008,.010),c*.20,.17+.29*fres+.05*structural);
  base+=c*(.035*fres+.022*structural*micro*sharp)*selected;
  float luma=dot(base,vec3(.2126,.7152,.0722));
  base=mix(vec3(luma)*vec3(.86,.94,.96),base,.68+.32*sharp);
  base=mix(base,vec3(.008,.013,.015),(.12*(1.-sharp)));
  base+=grain;
  outColor=vec4(pow(max(base,0.),vec3(.93)),1.);
}`
});

let selectedId='';
let renderContext=null;
let selectedField=null;
let selectionToken=0;
let focusMembers=null;
const overlay={field:null,svg:null,structure:null,worldById:null,edges:[],lineEls:[],nodeEls:[],raf:0};

function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function locusName(projection,gene){return projection?.phenotype?.[gene]||gene}
function rankOf(value){const m=String(value||'').match(/^(\d+)H\./);return m?`${m[1]}H`:'S'}
function identityFor(projection,pointId){
  for(const g of GENES){
    for(const item of projection?.groups?.[g]||[])if(item.id===pointId)return {id:item.id,title:item.title,locus:g,rank:'S',kind:'source'};
    for(const item of projection?.holons?.[g]||[])if(item.id===pointId)return {id:item.id,title:item.title,locus:g,rank:rankOf(item.id),kind:'holon'};
  }
  return null;
}
function parentsOf(projection,pointId){const meta=projection?.holon_meta?.[pointId];return Array.isArray(meta)&&Array.isArray(meta[0])?meta[0]:(projection?.parents?.[pointId]||[])}
function childrenIndex(projection){const out=new Map();for(const [child,meta] of Object.entries(projection?.holon_meta||{})){const parents=Array.isArray(meta)&&Array.isArray(meta[0])?meta[0]:[];for(const parent of parents){if(!out.has(parent))out.set(parent,[]);out.get(parent).push(child)}}return out}
function lineageTrace(projection,pointId){
  const edges=[],nodes=new Map();if(!pointId)return {mode:'none',edges,nodes};
  if(pointId.startsWith('S.')){const children=childrenIndex(projection),seen=new Set();nodes.set(pointId,0);const walk=(parent,depth)=>{for(const child of children.get(parent)||[]){const key=child+'←'+parent;if(seen.has(key))continue;seen.add(key);edges.push({child,parent,depth});if(!nodes.has(child)||nodes.get(child)>depth+1)nodes.set(child,depth+1);walk(child,depth+1)}};walk(pointId,0);return {mode:'descendants',edges,nodes}}
  const seen=new Set();nodes.set(pointId,0);const walk=(child,depth,stack)=>{if(stack.has(child))return;const nextStack=new Set(stack);nextStack.add(child);for(const parent of parentsOf(projection,child)){const key=child+'→'+parent;if(!seen.has(key)){seen.add(key);edges.push({child,parent,depth})}if(!nodes.has(parent)||nodes.get(parent)>depth+1)nodes.set(parent,depth+1);if(!parent.startsWith('S.'))walk(parent,depth+1,nextStack)}};walk(pointId,0,new Set());return {mode:'ancestry',edges,nodes};
}
function lineageStats(projection,pointId){const trace=lineageTrace(projection,pointId),ids=[...trace.nodes.keys()].filter(x=>x!==pointId);let sources=0,holons=0,depth=0;for(const x of ids){if(x.startsWith('S.'))sources++;else holons++;depth=Math.max(depth,trace.nodes.get(x)||0)}return {mode:trace.mode,sources,holons,depth,total:ids.length}}
function externalLabel(url,index){try{const u=new URL(url),host=u.hostname.replace(/^www\./,'');if(host==='doi.org')return 'DOI · published work';if(host==='arxiv.org')return 'arXiv · source';if(host==='github.com')return 'GitHub · upstream';if(host.includes('w3.org'))return 'W3C · canonical source';return `${host} · original source`}catch(_){return `original source ${index+1}`}}
function detailFor(projection,pointId){
  const base=identityFor(projection,pointId);if(!base)return null;
  if(base.kind==='source'){const meta=projection?.source_meta?.[pointId];if(Array.isArray(meta)){const urls=Array.isArray(meta[2])?meta[2]:[];return {...base,credit:meta[0]||'',metabolism:meta[1]||'tetrahedralized · 4V / 6E / 4F / 1T',externals:urls.map((url,i)=>({url,label:externalLabel(url,i)}))}}const credit=projection?.authors?.[pointId]||'',url=projection?.external?.[pointId]||'';return {...base,credit,metabolism:'tetrahedralized · 4V / 6E / 4F / 1T',externals:url?[{url,label:externalLabel(url,0)}]:[]}}
  const meta=projection?.holon_meta?.[pointId];if(Array.isArray(meta))return {...base,parents:meta[0]||[],metabolism:meta[1]||'recursive holon · 4V / 6E / 4F / 1T',feeling_signature:meta[2]||'',bound:meta[3]||''};return {...base,parents:projection?.parents?.[pointId]||[],metabolism:'recursive holon · 4V / 6E / 4F / 1T'};
}
function allPoints(projection){const points=[];for(const g of GENES){for(const s of projection?.groups?.[g]||[])points.push(Object.freeze({id:s.id,gene:g,kind:'source',label:s.title,meta:`source · ${locusName(projection,g)}`}));for(const h of projection?.holons?.[g]||[])points.push(Object.freeze({id:h.id,gene:g,kind:'holon',label:h.title,meta:`${rankOf(h.id)} holon · ${locusName(projection,g)}`}))}return points}
function countAt(projection,gene,kind){const rows=projection?.[kind]?.[gene];return Array.isArray(rows)?rows.length:0}
function fieldProjection(d){const children={};for(const g of GENES){const sources=countAt(d,g,'groups'),holons=countAt(d,g,'holons'),noun=d?.phenotype?.[g]||g;children[g]={noun,de:noun,en:noun,gene:DNA[g],one:{de:`${sources} Quellen · ${holons} Holons.`,en:`${sources} sources · ${holons} holons.`},children:{}}}return {source:{organism:'papers',home:d?.event_id||'papers'},root:{noun:'Papers',children},occupancy:{w:[],x:[],z:[],y:[]},points:allPoints(d)}}

function hash32(text){let h=2166136261>>>0;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)>>>0}h^=h>>>16;h=Math.imul(h,0x7feb352d)>>>0;h^=h>>>15;h=Math.imul(h,0x846ca68b)>>>0;h^=h>>>16;return h>>>0}
function random01(text,salt){return (hash32(text+'·'+salt)+1)/4294967297}
function pointInTet(tet,spec){let weights=[0,1,2,3].map(i=>-Math.log(Math.max(1e-7,random01(spec.id,i))));const s=weights.reduce((a,b)=>a+b,0);weights=weights.map(v=>v/s);const inset=spec.kind==='holon'?.40:.22;weights=weights.map(v=>(1-inset)*v+inset*.25);return [0,1,2].map(k=>weights.reduce((sum,w,i)=>sum+w*tet[i][k],0))}
function sub(a,b){return a.map((x,i)=>x-b[i])}
function qMul(a,b){const[w,x,y,z]=a,[v,i,j,k]=b;return [w*v-x*i-y*j-z*k,w*i+x*v+y*k-z*j,w*j-x*k+y*v+z*i,w*k+x*j-y*i+z*v]}
function qRot(q,p){const r=qMul(qMul(q,[0,...p]),[q[0],-q[1],-q[2],-q[3]]);return r.slice(1)}
function buildWorldMap(field){if(!N||!field?.projection?.root)return null;const structure=N.collectStructure(field.projection.root),byGene=new Map(),map=new Map();for(const g of Object.keys(geneIndex)){const exact=structure.leaves.find(c=>c.path===g),first=structure.leaves.find(c=>c.path?.startsWith(g));if(exact||first)byGene.set(g,exact||first)}for(const spec of field.projection.points||[]){const cell=byGene.get(spec.gene);if(cell)map.set(spec.id,pointInTet(cell.tet,spec))}return {structure,map}}
function projectWorld(field,structure,point,rect){if(!N||!W)return null;const path=W.scopeId===field.localScope?W.view:'',t=N.focusTarget(structure,path),q=qRot(W.orientation,sub(point,t.center)),scale=(rect.width<560?1.42:1.75)*t.scale,camZ=3.2,z=camZ-q[2]*scale,f=(rect.height/2)/Math.tan(Math.PI/6.6);return {x:rect.width/2+q[0]*scale*f/z,y:rect.height/2-q[1]*scale*f/z,z:q[2]}}
function ensureOverlay(field){if(!field?.element||!field?.canvas||!N||!W)return;if(overlay.field!==field){overlay.svg?.remove();overlay.field=field;overlay.svg=null;overlay.structure=null;overlay.worldById=null;overlay.edges=[];overlay.lineEls=[];overlay.nodeEls=[]}if(!overlay.svg){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('papers-lineage-overlay');svg.setAttribute('aria-hidden','true');field.element.append(svg);overlay.svg=svg;const built=buildWorldMap(field);overlay.structure=built?.structure||null;overlay.worldById=built?.map||null;if(!overlay.raf)overlay.raf=requestAnimationFrame(drawOverlay)}}
function traceFocused(edge){if(!focusMembers||!focusMembers.size)return false;return focusMembers.has(edge.child)||focusMembers.has(edge.parent)}
function rebuildOverlay(projection){if(!selectedField)return;ensureOverlay(selectedField);if(!overlay.svg)return;overlay.svg.replaceChildren();overlay.edges=lineageTrace(projection,selectedId).edges;overlay.lineEls=[];overlay.nodeEls=[];for(const edge of overlay.edges){const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.classList.add('papers-lineage-edge');line.dataset.depth=String(edge.depth);if(edge.depth===0)line.classList.add('papers-lineage-edge-immediate');if(edge.parent.startsWith('S.'))line.classList.add('papers-lineage-edge-source');if(traceFocused(edge))line.classList.add('papers-lineage-edge-focus');overlay.svg.append(line);overlay.lineEls.push({edge,line})}const nodes=new Map();for(const e of overlay.edges){nodes.set(e.parent,e.depth+1);if(e.depth>0)nodes.set(e.child,e.depth)}for(const [nodeId,depth] of nodes){const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.classList.add('papers-lineage-node');if(nodeId.startsWith('S.'))c.classList.add('papers-lineage-node-source');if(focusMembers?.has(nodeId))c.classList.add('papers-lineage-node-focus');c.setAttribute('r',nodeId.startsWith('S.')?'2.1':depth<=1?'3.1':'2.5');overlay.svg.append(c);overlay.nodeEls.push({nodeId,c})}overlay.svg.hidden=!selectedId||!overlay.edges.length}
function drawOverlay(){overlay.raf=requestAnimationFrame(drawOverlay);const field=overlay.field,svg=overlay.svg;if(!field||!svg||svg.hidden||!overlay.structure||!overlay.worldById||!W)return;const cr=field.canvas.getBoundingClientRect(),er=field.element.getBoundingClientRect();if(!cr.width||!cr.height||!er.width||!er.height)return;svg.setAttribute('viewBox',`0 0 ${er.width} ${er.height}`);const ox=cr.left-er.left,oy=cr.top-er.top;const pos=(nodeId)=>{const w=overlay.worldById.get(nodeId);if(!w)return null;const p=projectWorld(field,overlay.structure,w,cr);return p?{x:p.x+ox,y:p.y+oy,z:p.z}:null};for(const {edge,line} of overlay.lineEls){const a=pos(edge.child),b=pos(edge.parent);if(!a||!b){line.hidden=true;continue}line.hidden=false;line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y)}for(const {nodeId,c} of overlay.nodeEls){const p=pos(nodeId);if(!p){c.hidden=true;continue}c.hidden=false;c.setAttribute('cx',p.x);c.setAttribute('cy',p.y)}}
function setTraceFocus(members,projection){focusMembers=Array.isArray(members)&&members.length?new Set(members):null;rebuildOverlay(projection)}

function sectionLabel(text){return el('div','papers-detail-kicker',text)}
function row(label,value){if(value===undefined||value===null||value==='')return null;const n=el('div','papers-detail-row');n.append(el('span','papers-detail-label',label),el('span','papers-detail-value',String(value)));return n}
function safeBound(value){const s=String(value||'').trim();return s&&/[.!?…]$/.test(s)?s:''}
function selectPoint(pointId){const field=globalThis.SSSInterlocutorFields?.get(id);if(field&&typeof field.selectPoint==='function')field.selectPoint(pointId,true)}
function externalLink(item){const a=el('a','papers-external-link');a.href=item.url;a.target='_blank';a.rel='noopener noreferrer';a.append(el('span','papers-external-label',item.label||'original source'),el('span','papers-external-arrow','↗'));return a}
function sourceDetail(projection,d){const panel=el('article','papers-detail papers-detail-source');panel.dataset.organismId=d.id;const head=el('div','papers-detail-head'),identity=el('div','papers-detail-identity');identity.append(el('span','papers-detail-code',d.id),el('span','papers-detail-locus',`${d.locus} · ${locusName(projection,d.locus)}`));const close=el('button','papers-detail-close','×');close.type='button';close.setAttribute('aria-label','Close source');close.addEventListener('click',()=>selectPoint(''));head.append(identity,close);panel.append(head,el('h1','papers-detail-title',d.title));const original=el('section','papers-detail-section papers-original');original.append(sectionLabel('ORIGINAL WORK'),el('div','papers-source-credit',d.credit||'source credit unresolved'));if(d.type)original.append(el('p','papers-source-type',d.type));const links=el('div','papers-external-links');for(const item of d.externals||[])links.append(externalLink(item));if(links.childElementCount)original.append(links);panel.append(original);const metabolism=el('section','papers-detail-section papers-metabolism');metabolism.append(sectionLabel('PAPERS METABOLISM'));const receipt=row('closure',d.metabolism);if(receipt)metabolism.append(receipt);if(d.quickscope)metabolism.append(el('p','papers-metabolic-copy',d.quickscope));if(d.boundary)metabolism.append(sectionLabel('EPISTEMIC BOUNDARY'),el('p','papers-boundary-copy',d.boundary));panel.append(metabolism);const stats=lineageStats(projection,d.id);if(stats.total){const descendants=el('section','papers-detail-section papers-lineage');descendants.append(sectionLabel('WHAT GREW FROM THIS SOURCE'),el('p','papers-lineage-summary',`${stats.holons} descendant holons · ${stats.depth} relational generations`));panel.append(descendants)}return panel}
function parentButton(parentId,projection){const d=detailFor(projection,parentId),b=el('button','papers-parent');b.type='button';b.dataset.parentId=parentId;b.append(el('span','papers-parent-id',parentId),el('span','papers-parent-title',d?.title||parentId));b.addEventListener('click',()=>selectPoint(parentId));return b}
function holonDetail(projection,d){const panel=el('article','papers-detail papers-detail-holon');panel.dataset.organismId=d.id;const head=el('div','papers-detail-head'),identity=el('div','papers-detail-identity');identity.append(el('span','papers-detail-code',d.id),el('span','papers-detail-locus',`${d.rank||rankOf(d.id)} · ${d.locus} · ${locusName(projection,d.locus)}`));const close=el('button','papers-detail-close','×');close.type='button';close.setAttribute('aria-label','Close holon');close.addEventListener('click',()=>selectPoint(''));head.append(identity,close);panel.append(head,el('h1','papers-detail-title',d.title),el('div','papers-derived','DERIVED INSIDE PAPERS'));const metabolism=el('section','papers-detail-section papers-metabolism');metabolism.append(sectionLabel('PAPERS METABOLISM'));const receipt=row('closure',d.metabolism);if(receipt)metabolism.append(receipt);const feeling=row('feeling',d.feeling_signature);if(feeling)metabolism.append(feeling);const bound=safeBound(d.bound);if(bound)metabolism.append(el('p','papers-metabolic-copy',bound));panel.append(metabolism);const stats=lineageStats(projection,d.id),lineage=el('section','papers-detail-section papers-lineage');lineage.append(sectionLabel('LINEAGE · FOUR PARENTS'),el('p','papers-lineage-summary',`${stats.holons} ancestral holons · ${stats.sources} original sources · ${stats.depth} generations deep`));const parents=el('div','papers-parents');for(const parent of d.parents||[])parents.append(parentButton(parent,projection));lineage.append(parents);panel.append(lineage);const loading=el('section','papers-detail-section papers-inquiry-loading');loading.append(sectionLabel('INQUIRY'),el('p','papers-boundary-copy','Opening the selected organism’s public relational body…'));panel.append(loading);return panel}
function detailPanel(projection){if(!selectedId)return null;const d=detailFor(projection,selectedId);if(!d)return null;return selectedId.startsWith('S.')?sourceDetail(projection,d):holonDetail(projection,d)}
async function loadInquiry(pointId){return INQUIRY[pointId]||null}
function traceButton(label,members,projection){const b=el('button','papers-trace',label);b.type='button';b.addEventListener('click',()=>{const same=focusMembers&&members.length===focusMembers.size&&members.every(x=>focusMembers.has(x));setTraceFocus(same?null:members,projection)});return b}
function relationCard(kind,item,projection){const n=el('article',`papers-relation papers-relation-${kind}`),head=el('div','papers-relation-head');head.append(el('span','papers-relation-id',item.id||''),el('strong','papers-relation-title',item.title||''));if(Array.isArray(item.members)&&item.members.length)head.append(traceButton('trace',item.members,projection));n.append(head);if(item.text)n.append(el('p','papers-relation-copy',item.text));if(item.removal){const details=el('details','papers-removal'),summary=el('summary','papers-removal-summary','removal witness');details.append(summary,el('p','papers-removal-copy',item.removal));n.append(details)}return n}
function volumeSection(body,projection){const v=body?.volume;if(!v)return null;const s=el('section','papers-detail-section papers-inquiry-volume');s.append(sectionLabel('WHOLE · 1T'),el('h2','papers-inquiry-title',v.title||body.title||'whole-four closure'));if(v.text)s.append(el('p','papers-inquiry-copy',v.text));if(v.invariant)s.append(el('p','papers-volume-invariant',v.invariant));if(Array.isArray(v.removal)&&v.removal.length){const d=el('details','papers-removal papers-removal-volume'),sum=el('summary','papers-removal-summary','four-way necessity');d.append(sum);for(const x of v.removal)d.append(el('p','papers-removal-copy',x));s.append(d)}if(Array.isArray(v.members)&&v.members.length)s.append(traceButton('trace whole earning body',v.members,projection));return s}
function relationsSection(body,projection){if(!(body?.edges?.length||body?.faces?.length))return null;const s=el('section','papers-detail-section papers-inquiry-relations');s.append(sectionLabel('RELATIONS · 6E / 4F'));if(body.edges?.length){s.append(el('div','papers-rank-label','SIX PAIR RELATIONS'));const grid=el('div','papers-relations-grid');for(const item of body.edges)grid.append(relationCard('edge',item,projection));s.append(grid)}if(body.faces?.length){s.append(el('div','papers-rank-label','FOUR TRIPLE CLOSURES'));const grid=el('div','papers-relations-grid papers-faces-grid');for(const item of body.faces)grid.append(relationCard('face',item,projection));s.append(grid)}return s}
function metabolitesSection(body,projection){if(!body?.metabolites?.length)return null;const s=el('section','papers-detail-section papers-inquiry-metabolites');s.append(sectionLabel('METABOLITES · SURVIVING WISDOM'));const list=el('div','papers-metabolites');for(const m of body.metabolites){const card=el('article','papers-metabolite'),head=el('div','papers-metabolite-head'),identity=el('div','papers-metabolite-identity');identity.append(el('span','papers-metabolite-id',m.id||''),el('strong','papers-metabolite-title',m.title||''));head.append(identity);if(m.members?.length)head.append(traceButton(`trace ${m.earning||'earning body'}`,m.members,projection));card.append(head);if(m.earning){const earned=row('earned by',m.strengthened_by?`${m.earning} · strengthened by ${m.strengthened_by}`:m.earning);if(earned)card.append(earned)}if(m.text)card.append(el('p','papers-metabolite-copy',m.text));if(m.compression)card.append(el('p','papers-metabolite-compression',m.compression));list.append(card)}s.append(list);return s}
async function hydrateInquiry(panel,projection,pointId,token){const body=await loadInquiry(pointId);if(token!==selectionToken||selectedId!==pointId||!panel.isConnected)return;panel.querySelector('.papers-inquiry-loading')?.remove();if(!body){const pending=el('section','papers-detail-section papers-inquiry-pending');pending.append(sectionLabel('INQUIRY PORE'),el('p','papers-boundary-copy','The lineage is fully traversable here. This organism’s readable 6E / 4F / 1T and metabolite body has not yet been admitted to the public site projection.'));panel.append(pending);return}const volume=volumeSection(body,projection),relations=relationsSection(body,projection),metabolites=metabolitesSection(body,projection);if(volume)panel.append(volume);if(relations)panel.append(relations);if(metabolites)panel.append(metabolites);if(body.boundary){const b=el('section','papers-detail-section papers-inquiry-boundary');b.append(sectionLabel('EPISTEMIC BOUNDARY'),el('p','papers-boundary-copy',body.boundary));panel.append(b)}}
function hud(projection){const p=projection.population||{},n=el('div','papers-hud'),line=el('div','papers-hud-line');line.append(el('strong','papers-hud-title','Papers'),el('span','papers-hud-stat',`${p.registry_sources??0} sources · ${p.holons??0} holons`));const legend=el('div','papers-legend'),source=el('span','papers-legend-item');source.append(el('i','papers-legend-dot'),document.createTextNode(' source'));const holon=el('span','papers-legend-item');holon.append(el('i','papers-legend-diamond'),document.createTextNode(' holon'));legend.append(source,holon,el('span','papers-hud-help','hover · click to inquire'));n.append(line,legend);return n}
function paintSelection(){if(!renderContext)return;const {content,projection}=renderContext;const old=content.querySelector('.papers-detail');if(old)old.remove();focusMembers=null;rebuildOverlay(projection);const panel=detailPanel(projection);if(panel){content.append(panel);if(!selectedId.startsWith('S.')){const token=++selectionToken;hydrateInquiry(panel,projection,selectedId,token)}}}
function activateFieldPoint({point,field}={}){selectedField=field||globalThis.SSSInterlocutorFields?.get(id)||selectedField;selectedId=point?.id||'';if(selectedField)ensureOverlay(selectedField);paintSelection()}
function render({host,content,projection}={}){if(!host||!content||!projection?.groups||!projection?.phenotype)return false;host.hidden=false;content.className='interlocutor-content papers-content';content.replaceChildren();renderContext={host,content,projection};selectedField=globalThis.SSSInterlocutorFields?.get(id)||selectedField;if(selectedField)ensureOverlay(selectedField);content.append(hud(projection));paintSelection();return true}
function unmount({host,content}={}){selectionToken++;selectedId='';focusMembers=null;renderContext=null;if(overlay.svg){overlay.svg.hidden=true;overlay.svg.replaceChildren()}if(host)host.hidden=true;if(content)content.replaceChildren()}
modules.set(id,Object.freeze({id,shader,render,unmount,fieldProjection,activateFieldPoint}));
})();
